train:
    description: Train a model.
    main: pytorch_med_imaging.main
    flags:
        config: "Configs/Survival/Test.ini"
        epoch: 50
        batch-size: 4
        lr: 1E-4
        debug: no
        override: ""
    output-scalars:
        loss/loss: 'EpochLoss: (\value)'
        accuracy: 'ACC: (\value)'
        loss/validation_loss: 'VAL: (\value)'
        step: 'Epoch (\step)'
        step_lr: 'LR: (\value)'
    sourcecode:
        root: ../
        select: 
            - exclude:
                dir: 'NPC_Segmentation'
            - exclude:
                dir: 'Backup'
            - exclude:
                dir: '__pycache__'
            - exclude: 
                dir: "Guildai"
            - '*.py'
            - '*.pyx'
            - '*.txt'
            - '*.so'
    requires:
        - file: '../Configs'
        - file: '../NPC_Segmentation'
        - file: '../Sinus'
        - file: '../Backup/Log'

train_segment:
    description: Train a model.
    main: pytorch_med_imaging.main
    flags:
        config: "Configs/Survival/Test.ini"
        epoch: 50
        batch-size: 4
        lr: 1E-4
        debug: no
        override: ""
    output-scalars:
        loss/loss: 'EpochLoss: (\value)'
        perf/accuracy: 'ACC: (\value)'
        perf/dsc: 'DSC: (\value)'
        loss/validation_loss: 'VAL: (\value)'
        step: 'Epoch (\step)'
        step_lr: 'LR: (\value)'
    sourcecode:
        root: ../
        select:
            - exclude:
                  dir: 'NPC_Segmentation'
            - exclude:
                  dir: 'Backup'
            - exclude:
                  dir: '__pycache__'
            - exclude:
                  dir: "Guildai"
            - '*.py'
            - '*.pyx'
            - '*.txt'
            - '*.so'
    requires:
        - file: '../Configs'
        - file: '../NPC_Segmentation'
        - file: '../Sinus'
        - file: '../Backup/Log'

train_survival:
    description: Train a model.
    main: pytorch_med_imaging.main
    flags:
        config: "Configs/Survival/Test.ini"
        epoch: 50
        batch-size: 4
        lr: 1E-4
        debug: no
        override: ""
    output-scalars:
        loss/loss: 'EpochLoss: (\value)'
        loss/validation_loss: 'VAL: (\value)'
        step: 'Epoch (\step)'
        step_lr: 'LR: (\value)'
        perf/validation_c-index: 'VAL C-index: (\value)'
        perf/training_c-index: 'Training C-index: (\value)'
    sourcecode:
        root: ../
        select:
            - exclude:
                dir: 'NPC_Segmentation'
            - exclude:
                dir: 'Backup'
            - exclude:
                dir: '__pycache__'
            - exclude:
                dir: "Guildai"
            - '*.py'
            - '*.pyx'
            - '*.txt'
            - '*.so'
    requires:
        - file: '../Configs'
        - file: '../NPC_Segmentation'
        - file: '../Backup/Log'

validation:
    decription: Validate the trained model. Should be used in pipeline, otherwise it won't find the checkpoint.
    main: pytorch_med_imaging.main --inference
    flags:
        batch-size: 4
        config: "Configs/Survival/Test.ini"
        override: ""
    sourcecode:
        root: ../
        select:
            - exclude:
                dir: 'NPC_Segmentation'
            - exclude:
                dir: '__pycache__'
            - exclude:
                dir: "Guildai"
            - '*.py'
            - '*.pyx'
            - '*.txt'
            - '*.so'
    requires:
        - file: '../Configs'
        - file: '../NPC_Segmentation'
        - file: '../Sinus'
        - operation: train
          select: 'Backup'
    output-scalars:
        sensitivity: 'Sensitivity: (\value)'
        specificity: 'Specificity: (\value)'
        PPV: 'PPV: (\value)'
        NPV: 'NPV: (\value)'
        ACC: 'OverallACC: (\value)'

validation_segment:
    decription: Validate the trained model. Should be used in pipeline, otherwise it won't find the checkpoint.
    main: pytorch_med_imaging.main --inference
    flags:
        batch-size: 4
        config: "Configs/Survival/Test.ini"
        override: ""
    sourcecode:
        root: ../
        select:
            - exclude:
                  dir: 'NPC_Segmentation'
            - exclude:
                  dir: '__pycache__'
            - exclude:
                  dir: "Guildai"
            - '*.py'
            - '*.pyx'
            - '*.txt'
            - '*.so'
    requires:
        - file: '../Configs'
        - file: '../NPC_Segmentation'
        - file: '../Sinus'
        - operation: train_segment
          select: 'Backup'
    output-scalars:
        DSC: 'Avg_DICE: (\value)'
        med_DSC: 'Med_DICE: (\value)'


validation_survival:
    decription: Validate the trained model. Should be used in pipeline, otherwise it won't find the checkpoint.
    main: pytorch_med_imaging.main --inference
    flags:
        batch-size: 4
        config: "Configs/Survival/Test.ini"
        override: ""
    sourcecode:
        root: ../
        select:
            - exclude:
                  dir: 'NPC_Segmentation'
            - exclude:
                  dir: '__pycache__'
            - exclude:
                  dir: "Guildai"
            - '*.py'
            - '*.pyx'
            - '*.txt'
            - '*.so'
    requires:
        - file: '../Configs'
        - file: '../NPC_Segmentation'
        - operation: train_survival
          select: 'Backup'
    output-scalars:
        C-index: 'C-index: (\value)'


pipeline:
    flags:
        config: "Configs/Survival/Test.ini"
        epoch: 50
        batch-size: 4
        lr: 1E-4
        override: ""
    steps:
        - train config=${config} epoch=${epoch} batch-size=${batch-size} lr=${lr} override=${override}
        - validation config=${config} batch-size=${batch-size} override=${override}

pipeline_segment:
    flags:
        config: "Configs/Survival/Test.ini"
        epoch: 50
        batch-size: 4
        lr: 1E-4
        override: ""
    steps:
        - train_segment config=${config} epoch=${epoch} batch-size=${batch-size} lr=${lr} override=${override}
        - validation_segment config=${config} batch-size=${batch-size} override="${override};(LoaderParams,random_patches)=75"

pipeline_survival:
    flags:
        config: "Configs/Survival/Test.ini"
        epoch: 50
        batch-size: 4
        lr: 1E-4
        override: ""
    steps:
        - train_survival config=${config} epoch=${epoch} batch-size=${batch-size} lr=${lr} override=${override}
        - validation_survival config=${config} batch-size=${batch-size} override=${override}